name: Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  build_and_release:
    name: Build and release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"
      - name: Install
        run: npm ci
      - name: Build
        run: |
          npm run build
      - name: Update Package Version
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          CURRENT_VERSION=$(node -pe "require('./package.json').version")
          NEW_VERSION="${CURRENT_VERSION}-rc-${COMMIT_HASH}"
          echo "Updating package version to $NEW_VERSION"
          npm version $NEW_VERSION --no-git-tag-version
      - run: npm publish --tag rc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
